name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

env:
  NODE_VERSION: "18"
  REGISTRY: docker.io # Change this to your container registry (e.g., Docker Hub or GitHub Container Registry)
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-api-app

      - name: Run Tests inside container
        run: docker run my-api-app npm test
